(deftheme purple
  "Created 2014-05-17.")

(custom-theme-set-faces
 'purple
 '(cursor ((t (:weight normal :underline nil :foreground "#101010" :background "#cccccc"))))
 '(fixed-pitch ((t (:family "PragmataPro" :weight normal :underline nil))))
 '(variable-pitch ((t (:family "Sans Serif" :weight normal :underline nil))))
 '(escape-glyph ((t (:weight normal :underline nil :foreground "#d1afdd"))))
 '(minibuffer-prompt ((t (:weight normal :underline nil :foreground "#d1afdd"))))
 '(highlight ((t (:weight normal :underline nil :background "#31182d"))))
 '(region ((t (:weight normal :underline nil :background "#412b3f"))))
 '(shadow ((t (:weight normal :underline nil :foreground "grey70"))))
 '(secondary-selection ((t (:weight normal :underline nil :background "#3f3f3f"))))
 '(trailing-whitespace ((t (:weight normal :underline nil :background "#d1afdd"))))
 '(font-lock-builtin-face ((t (:weight normal :underline nil :foreground "#ddd"))))
 '(font-lock-comment-delimiter-face ((t (:weight normal :underline nil :foreground "#555" :inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:weight normal :underline nil :foreground "#755273"))))
 '(font-lock-constant-face ((t (:weight normal :underline nil :foreground "#B294BB"))))
 '(font-lock-doc-face ((t (:weight normal :underline nil :foreground "#a582a3" :inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:weight normal :underline nil :foreground "#EFEFEF"))))
 '(font-lock-keyword-face ((t (:weight normal :underline nil :foreground "#d1afdd"))))
 '(font-lock-negation-char-face ((t (:weight normal :underline nil :foreground "#cccccc"))))
 '(font-lock-preprocessor-face ((t (:weight normal :underline nil :foreground "#d1afdd" :inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:weight normal :underline nil :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:weight normal :underline nil :inherit (bold)))))
 '(font-lock-string-face ((t (:weight normal :underline nil :foreground "#a582a3"))))
 '(font-lock-type-face ((t (:weight normal :underline nil :foreground "#e0e0e0"))))
 '(font-lock-variable-name-face ((t (:weight normal :underline nil :foreground "#787878"))))
 '(font-lock-warning-face ((t (:weight normal :underline nil :foreground "#c0af7f" :inherit (error)))))
 '(button ((t (:inherit link :foreground "#f0dfff" :underline t :weight normal))))
 '(link ((t (:foreground "#f0dfff" :underline t :weight normal))))
 '(link-visited ((t (:inherit link :foreground "#d0bfdf" :underline t :weight normal))))
 '(fringe ((t (:weight normal :underline nil :foreground "#585858" :background "#191919"))))
 '(header-line ((t (:weight normal :underline nil :box nil :foreground "grey90" :background "grey20" :inherit (mode-line)))))
 '(tooltip ((t (:weight normal :underline nil :foreground "#d1afdd" :background "#292929" :inherit (variable-pitch)))))
 '(mode-line ((t (:weight normal :underline nil :box nil :foreground "#d1afdd" :background "#2b2b2b"))))
 '(mode-line-buffer-id ((t (:weight normal :underline nil :foreground "#f0dfff"))))
 '(mode-line-emphasis ((t (:weight normal :underline nil))))
 '(mode-line-highlight ((t (:weight normal :underline nil :box nil))))
 '(mode-line-inactive ((t (:weight normal :underline nil :box nil :foreground "#a582a3" :background "#202020" :inherit (mode-line)))))
 '(isearch ((t (:weight normal :underline nil :foreground "#d1afdd" :background "#2b2b2b"))))
 '(isearch-fail ((t (:weight normal :underline nil :foreground "#d1afdd" :background "#856283"))))
 '(lazy-highlight ((t (:weight normal :underline nil :foreground "#dfafdf" :background "#2f2f2f"))))
 '(match ((t (:weight normal :underline nil :foreground "#dfafdf" :background "#2b2b2b"))))
 '(next-error ((t (:weight normal :underline nil :inherit (region)))))
 '(query-replace ((t (:weight normal :underline nil :inherit (isearch)))))
 '(default ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :height 90 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#cccccc" :background "#101010" :stipple nil :inherit nil)))))

(provide-theme 'purple)
